### PR TITLE
[Ashish] - Making changes to add and display players

### PR DESCRIPTION
**Pull request by kingkada**
Made changes to add players and display them [in progress]

### CODE REVIEW

**Comment by eltonstewart** [comment]
Guys. How come you didn’t check this change with me!?

**Comment by kingkada** [comment]
@eltonstewart : Didn't realise you we had a PO for this.

**Comment by eltonstewart** [comment]
Haha. I think we should all sit down and discuss the road map.

**Review by piyush8098 — APPROVED** [review]
Cool

**Pull request merged**
